name: Deploy Databricks Asset Bundle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Databricks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Databricks CLI
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli
      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          cat > ~/.databricks/credentials << EOF
          [DEFAULT]
          host = ${{ secrets.DATABRICKS_HOST }}
          token = ${{ secrets.DATABRICKS_TOKEN }}
          EOF
          chmod 600 ~/.databricks/credentials
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          databricks bundle deploy --target dev
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          databricks bundle deploy --target prod
