name: Deploy Databricks Asset Bundle

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Databricks CLI v2
        run: |
          pip install databricks-cli databricks-sdk

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databricks/credentials
          echo "host = $DATABRICKS_HOST" >> ~/.databricks/credentials
          echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/credentials
          chmod 600 ~/.databricks/credentials

      - name: Deploy to Production
        working-directory: deployment
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy --target prod
