name: Deploy Databricks Asset Bundle

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Databricks CLI v2
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
          databricks --version

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

      - name: Deploy to Production
        working-directory: deployment
        run: |
          databricks bundle deploy --target prod
